# Directory where fastq files are stored
fastqdir: /home1/wangchenfei/Project/SingleCell/SpatialTrans/Analysis/10X_brain_coronal/Data/V1_Adult_Mouse_Brain_fastqs

# Sample name of fastq file
# For example, if there is a file named V1_Adult_Mouse_Brain_S5_L001_I1_001.fastq.gz, the sample name is "V1_Adult_Mouse_Brain".
fastqprefix: V1_Adult_Mouse_Brain

# Brightfield tissue H&E image in .jpg or .tiff format.
image: /home1/wangchenfei/Project/SingleCell/SpatialTrans/Analysis/10X_brain_coronal/Data/V1_Adult_Mouse_Brain_image.tif

# Visium slide serial number, for example V10J25-015.
slide: V19L01-041

# Visium area identifier, for example A1.
area: C1

# The prefix of output files. DEFAULT: MAESTRO.
outprefix: 10X_brain_coronal

# Number of cores to use
cores: 8

# Cell signature file used to annotate cell types. MAESTRO provides several sets of built-in cell signatures. 
# Users can choose from ['human.immune.CIBERSORT', 'mouce.brain.ALLEN', 'mouse.all.facs.TabulaMuris', 'mouse.all.droplet.TabulaMuris']. 
# Custom cell signatures are also supported. In this situation, users need to provide the file location of cell signatures, 
# and the signature file is tab-seperated without header. The first column is cell type, and the second column is signature gene.
signature: mouce.brain.ALLEN

# Reference genome 
genome:
  # Path of folder containing 10x-compatible reference
  mapindex: /home1/wangchenfei/annotations/refdata-cellranger-mm10-3.0.0
